name             'artifactory'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures artifactory'
long_description 'Installs/Configures artifactory'
version          '0.1.0'
